### ISSUE TITLE
Tests that crash on pipeline

### ISSUE THREAD

**Issue by aneojgurhem** [aneoconsulting/ArmoniK.Core#544]
Windows:

- [x] MultipleWatchShouldSucceed
- [x] ExecuteTaskShouldSucceed
- [x] ArmoniK.Extensions.Common.StreamWrapper.Tests.Client.TaskSubmissionTests ► SubmitTasksShouldSucceed
- [x] ArmoniK.Core.Common.Tests.WatchToGrpcTests ► MultipleWatchShouldSucceed https://github.com/aneoconsulting/ArmoniK.Core/pull/854
- [x] ArmoniK.Core.Common.Tests.Pollster.TaskHandlerTest ► ExecuteTaskWithExceptionDuringCancellationShouldSucceed(UnavailableAfterCancellation)
- [x] ArmoniK.Core.Common.Tests.Pollster.PollsterTest -> ExecuteTaskThatExceedsGraceDelayShouldResubmit #826 
- [x] ArmoniK.Core.Common.Tests.Pollster.PollsterTest -> ExecuteTaskShouldSucceed #826 
- [x] ArmoniK.Core.Common.Tests.Pollster.PollsterTest ► ExecuteTaskTimeoutAcquire #826

Rabbitmq (to monitor):
- https://github.com/aneoconsulting/ArmoniK.Core/actions/runs/7726977568/attempts/65
